# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Betancur
email: johnnyazee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wow!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnbetancur.com" # the base hostname & protocol for your site
twitter_username: conundramatic
github_username:  jbetancur

# Build settings
markdown: kramdown

destination: public
#source: src

exclude:
- webpack
- node_modules
- package.json

sass:
  style: compressed

layout: compress